/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#bb152c",
        "on-primary-fixed": "#410007",
        "on-tertiary": "#003731",
        "surface-variant": "#353437",
        "background": "#131315",
        "outline-variant": "#5b403f",
        "primary": "#ffb3b1",
        "secondary-container": "#fbb400",
        "on-secondary": "#422c00",
        "primary-container": "#ff535b",
        "on-tertiary-container": "#00302a",
        "on-secondary-container": "#694900",
        "on-tertiary-fixed": "#00201c",
        "surface-bright": "#39393b",
        "tertiary-fixed": "#8cf5e4",
        "surface-container-low": "#1b1b1d",
        "inverse-on-surface": "#303032",
        "tertiary-container": "#30a193",
        "surface-dim": "#131315",
        "on-primary": "#680011",
        "surface-container-highest": "#353437",
        "parchment": "#F1FAEE",
        "outline": "#ab8987",
        "muted": "#8D99AE",
        "surface-container-lowest": "#0e0e10",
        "primary-fixed": "#ffdad8",
        "error": "#ffb4ab",
        "surface-container": "#201f21",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005048",
        "surface-container-high": "#2a2a2c",
        "on-primary-fixed-variant": "#92001c",
        "secondary-fixed-dim": "#ffba27",
        "on-surface-variant": "#e4bebc",
        "on-error": "#690005",
        "secondary-fixed": "#ffdea9",
        "surface-tint": "#ffb3b1",
        "on-surface": "#e5e1e4",
        "secondary": "#ffd795",
        "surface": "#1E1E24",
        "on-secondary-fixed": "#271900",
        "primary-fixed-dim": "#ffb3b1",
        "inverse-surface": "#e5e1e4",
        "on-primary-container": "#5b000e",
        "on-background": "#e5e1e4",
        "tertiary": "#6fd8c8",
        "tertiary-fixed-dim": "#6fd8c8",
        "on-secondary-fixed-variant": "#5e4100"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "border-width": "3px"
      },
      fontFamily: {
        "headline-lg": ["Bricolage Grotesque", "sans-serif"],
        "headline-xl": ["Bricolage Grotesque", "sans-serif"],
        "headline-md": ["Bricolage Grotesque", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
